### ISSUE TITLE
[Feature] unicode character lookup by description

### ISSUE THREAD

**Issue by Adjective-Object** [antifuchs/chars#2]
Being able to quickly look up a unicode character from your terminal could prove very useful (being able to call `cha` from vim, for example).

Is this in scope? If so I might submit a pull trying to implement this.

**Comment by antifuchs** [comment]
This is definitely in scope! One of the next things that I was going to look at is importing the fancy character names (`'\n'`, `'bang`, etc) from `ascii(1)`'s tables.

**Comment by antifuchs** [comment]
A bit of an update here: I merged my work on importing the `ascii(1)` nametable in 5438df3cffff6744fddeec3118ee4072630591ec, and am currently working on getting some reasonable search functions for unicode character names (based in [fst](http://burntsushi.net/rustdoc/fst/), probably). Hope that this will let us all run `chars smile` and get all the friendly faces back! (:
