### ISSUE TITLE
`cargo install` fails

### ISSUE THREAD

**Issue by jean** [antifuchs/chars#26]
When naively doing `cargo install` following the README, it fails with:

```
13:25~/git/chars(master)$ cargo install
error: found a virtual manifest at `/data/data/com.termux/files/home/git/chars/Cargo.toml` instead of a package manifest
```

`cargo install chars --git https://github.com/antifuchs/chars.git` works fine.

**Comment by antifuchs** [comment]
Argh, yep, this is due to the restructuring the repo underwent. I need to update the readme: The correct install command is `cargo install --path chars` from inside the repo.
