### ISSUE TITLE
AUR Package

### ISSUE THREAD

**Issue by wezm** [antifuchs/chars#6]
Hi, thanks for building this.

Just thought I'd let you know that I've added an [AUR package](https://aur.archlinux.org/packages/chars/) for chars to make it easy to install on Arch Linux with the system packaging tools.

Might be worth including a link to the package in installation section of the README.

**Comment by antifuchs** [comment]
Thanks so much for packaging this! I updated the README to point to the AUR page (:

**Comment by wezm** [comment]
Great, thank you :-)
